apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  namespace: piyush
  labels:
    app: app-dev
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1           # How many extra pods can be created above the desired number
      maxUnavailable: 1    
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
      - name: odoo-deployment
        image: piyushj01/odoo
        ports:
        - containerPort: 80 
